version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    env_file: .env
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/c/Users/famal/volumes/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/c/Users/famal/volumes/wordpress
      o: bind

networks:
  inception:
    driver: bridge